//! Custom zsh completion generator for the git-tidy dispatcher.
//!
//! Generates a `_git-tidy` zsh completion function that:
//! - Completes dispatch aliases (from `TOOL_SPECS`) at position 1
//! - Delegates to per-tool completers (`_git-<tool>-tidy`) for deeper args
//! - Completes `audit` flags via clap introspection

use std::io::{self, Write};

use clap::CommandFactory;

use crate::cli;
use crate::types::TOOL_SPECS;

/// Generate a custom zsh completion script for `git-tidy`.
pub fn generate_zsh(out: &mut dyn Write) -> io::Result<()> {
    writeln!(out, "#compdef git-tidy")?;
    writeln!(out)?;
    writeln!(out, "# Auto-generated by git-tidy. Do not edit.")?;
    writeln!(out)?;

    // Collect all aliases for the compadd list
    let mut aliases: Vec<&str> = Vec::new();
    for spec in TOOL_SPECS {
        for alias in spec.aliases {
            aliases.push(alias);
        }
    }
    aliases.push("audit");
    aliases.push("explain");

    // Introspect audit flags from clap
    let audit_flags = introspect_audit_flags();

    // Build the zsh function
    writeln!(out, "_git-tidy() {{")?;
    writeln!(out, "  local curcontext=\"$curcontext\" state line")?;
    writeln!(out, "  typeset -A opt_args")?;
    writeln!(out)?;
    writeln!(out, "  _arguments -C '1:command:->cmd' '*::arg:->args'")?;
    writeln!(out)?;
    writeln!(out, "  case $state in")?;

    // cmd state: complete aliases + audit
    writeln!(out, "    cmd)")?;
    write!(out, "      local -a commands=(")?;
    for alias in &aliases {
        write!(out, " '{alias}'")?;
    }
    writeln!(out, " )")?;
    writeln!(out, "      _describe 'command' commands")?;
    writeln!(out, "      ;;")?;

    // args state: delegate to sub-tool completers or complete audit flags
    writeln!(out, "    args)")?;
    writeln!(out, "      case ${{line[1]}} in")?;

    // For each tool spec, map all its aliases to the tool's completer.
    // Prepend the binary name to words (since '*::arg:->args' already
    // stripped the alias) so the sub-tool's completion function sees the
    // expected command context.
    for spec in TOOL_SPECS {
        let patterns: Vec<&str> = spec.aliases.to_vec();
        let pattern = patterns.join("|");
        let bin = spec.binary;
        writeln!(out, "        {pattern})")?;
        writeln!(out, "          words=({bin} \"${{words[@]}}\")")?;
        writeln!(out, "          (( CURRENT++ ))")?;
        writeln!(out, "          _{bin}")?;
        writeln!(out, "          ;;")?;
    }

    // explain subcommand (no flags, just pass-through)
    writeln!(out, "        explain)")?;
    writeln!(out, "          ;;")?;

    // audit subcommand
    writeln!(out, "        audit)")?;
    write!(out, "          _arguments")?;
    for flag in &audit_flags {
        write!(out, " '{flag}'")?;
    }
    writeln!(out)?;
    writeln!(out, "          ;;")?;

    writeln!(out, "      esac")?;
    writeln!(out, "      ;;")?;
    writeln!(out, "  esac")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Standard zsh completion files only define the completion function and let `compinit` invoke it. The previous `(( $+functions[_git-tidy] )) || _git-tidy "$@"` line both inverted the intent ("call it if NOT defined" — but it was just defined) and invoked the function at source-time with whatever args the user happened to source the file with. Remove it.

    Ok(())
}

/// Escape a string for embedding inside a zsh `_arguments` flag spec like `'--foo[description]'`.
///
/// Two nested quoting layers apply:
/// 1. The outer single-quoted shell string. Single quotes cannot be backslash-escaped
///    inside `'...'` in zsh; the only way to embed one is the standard close-escape-reopen
///    idiom `'\''` (end the literal, output an escaped quote, start a new literal).
///    Backslash and `$` are not special inside `'...'`, so they pass through verbatim.
/// 2. The inner `_arguments` spec description `[...]`. The spec parser treats `]`, `:`,
///    and `\` as significant; an unescaped `]` closes the description early, `:` introduces
///    an argument expression, and `\` is the spec's own escape character. These must be
///    backslash-escaped so the spec parser sees them as literal text. Because backslash
///    is not special in the outer single-quoted layer, the literal `\]` written here
///    reaches the spec parser intact.
fn escape_zsh_help(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            // Outer layer: close the single-quoted string, emit a literal `'`, reopen.
            '\'' => out.push_str("'\\''"),
            // Inner layer: spec-significant characters in `[...]`.
            '\\' | ']' | ':' => {
                out.push('\\');
                out.push(ch);
            }
            // Collapse newlines/tabs so the help fits on one line in the spec.
            '\n' | '\t' => out.push(' '),
            _ => out.push(ch),
        }
    }
    out
}

/// Extract audit subcommand flags from the clap `Command` struct.
fn introspect_audit_flags() -> Vec<String> {
    let cmd = cli::Cli::command();
    let mut flags = Vec::new();

    for sub in cmd.get_subcommands() {
        if sub.get_name() == "audit" {
            for arg in sub.get_arguments() {
                if arg.get_id() == "help" {
                    continue;
                }
                let long = arg.get_long().unwrap_or_default();
                if !long.is_empty() {
                    let raw_help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
                    let help = escape_zsh_help(&raw_help);
                    flags.push(format!("--{long}[{help}]"));
                }
            }
            break;
        }
    }

    flags
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated_output() -> String {
        let mut buf = Vec::new();
        generate_zsh(&mut buf).unwrap();
        String::from_utf8(buf).unwrap()
    }

    #[test]
    fn output_starts_with_compdef() {
        let output = generated_output();
        assert!(output.starts_with("#compdef git-tidy"));
    }

    #[test]
    fn output_contains_all_tool_aliases() {
        let output = generated_output();
        for spec in TOOL_SPECS {
            for alias in spec.aliases {
                assert!(
                    output.contains(&format!("'{alias}'")),
                    "missing alias {alias:?} in completions output"
                );
            }
        }
    }

    #[test]
    fn output_contains_audit() {
        let output = generated_output();
        assert!(output.contains("'audit'"));
    }

    #[test]
    fn output_contains_explain() {
        let output = generated_output();
        assert!(output.contains("'explain'"));
    }

    #[test]
    fn output_contains_audit_flags() {
        let output = generated_output();
        assert!(output.contains("--json"), "missing --json audit flag");
        assert!(
            output.contains("--porcelain"),
            "missing --porcelain audit flag"
        );
        assert!(output.contains("--verbose"), "missing --verbose audit flag");
        assert!(output.contains("--tools"), "missing --tools audit flag");
        assert!(
            output.contains("--subprocess"),
            "missing --subprocess audit flag"
        );
    }

    #[test]
    fn output_contains_tool_delegation() {
        let output = generated_output();
        for spec in TOOL_SPECS {
            let bin = spec.binary;
            assert!(
                output.contains(&format!("_{bin}")),
                "missing delegation call for {bin}"
            );
            assert!(
                output.contains(&format!("words=({bin}")),
                "missing words prepend for {bin}"
            );
        }
    }

    #[test]
    fn output_does_not_invoke_itself_at_source_time() {
        // Regression: previously the file ended with `(( $+functions[_git-tidy] )) || _git-tidy "$@"`, which both inverted the intent and ran the completion function the moment the file was sourced. Standard compinit-driven completion files don't do this.
        let output = generated_output();
        assert!(
            !output.contains("$+functions[_git-tidy]"),
            "should not gate on $+functions",
        );
        assert!(
            !output.contains("_git-tidy \"$@\""),
            "should not invoke _git-tidy at source time",
        );
    }

    #[test]
    fn audit_help_with_metacharacters_is_escaped() {
        // Regression: the audit `--tools` help contains a comma-separated, quoted example. Previously the raw help (including any future `:` or `]` characters) was dropped into a zsh `_arguments` spec verbatim, producing malformed completion strings the first time someone added a colon or bracket to help text. Locking in that escape_zsh_help is actually invoked on the help.
        let flags = introspect_audit_flags();
        let tools = flags
            .iter()
            .find(|f| f.starts_with("--tools["))
            .expect("--tools flag must exist");
        // Sanity check: the helper does not let any unescaped `]` reach output (apart from the terminating bracket).
        let inner = tools
            .strip_prefix("--tools[")
            .and_then(|s| s.strip_suffix(']'))
            .expect("--tools spec must be [..]-delimited");
        assert!(
            !inner.contains(']') || inner.contains("\\]"),
            "any `]` inside the bracket must be backslash-escaped, got {inner:?}",
        );
    }

    /// Pipe `script` through `zsh -n` (syntax-only). Returns `None` if `zsh` is not on
    /// PATH (so the test can skip gracefully on Linux CI containers without zsh installed),
    /// `Some(Ok(()))` on success, or `Some(Err(stderr))` on syntax error.
    fn zsh_syntax_check(script: &str) -> Option<Result<(), String>> {
        use std::io::Write;
        let mut child = match std::process::Command::new("zsh")
            .arg("-n")
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .spawn()
        {
            Ok(c) => c,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return None,
            Err(e) => panic!("spawn zsh: {e}"),
        };
        child
            .stdin
            .as_mut()
            .unwrap()
            .write_all(script.as_bytes())
            .unwrap();
        let result = child.wait_with_output().expect("wait zsh");
        if result.status.success() {
            Some(Ok(()))
        } else {
            Some(Err(String::from_utf8_lossy(&result.stderr).into_owned()))
        }
    }

    #[test]
    fn generated_completion_parses_as_zsh() {
        // End-to-end syntax check: pipe the full generated completion script through
        // `zsh -n`. This catches escape bugs that only surface when help text or aliases
        // sit inside the surrounding `'...'` quoting layer. Skipped on hosts without zsh.
        let output = generated_output();
        let Some(result) = zsh_syntax_check(&output) else {
            eprintln!("skipping: zsh not installed on this host");
            return;
        };
        if let Err(stderr) = result {
            panic!("zsh -n rejected generated completion:\nstderr: {stderr}");
        }
    }

    #[test]
    fn escape_zsh_help_escapes_special_chars() {
        let escaped = escape_zsh_help("describe ]: \\backslash");
        assert!(escaped.contains("\\]"));
        assert!(escaped.contains("\\:"));
        assert!(escaped.contains("\\\\"));
    }

    #[test]
    fn escape_zsh_help_uses_close_reopen_idiom_for_apostrophe() {
        // Regression: a naive `'` -> `\'` mapping is broken inside zsh single-quoted strings,
        // where backslash is not an escape character. The standard idiom is to terminate the
        // outer single-quoted literal, emit a backslash-escaped quote, then reopen.
        let escaped = escape_zsh_help("don't");
        assert_eq!(escaped, "don'\\''t");
    }

    #[test]
    fn escape_zsh_help_does_not_escape_dollar() {
        // `$` is literal inside a zsh single-quoted string. Backslash-escaping it would
        // produce a stray `\$` in completion menu text, since the `_arguments` spec
        // parser does not treat `$` as significant either.
        let escaped = escape_zsh_help("price $5");
        assert_eq!(escaped, "price $5");
    }

    #[test]
    fn escape_zsh_help_output_parses_as_zsh_when_embedded_in_arguments_spec() {
        // End-to-end: embed escaped help in a real `_arguments` flag spec and verify
        // that `zsh -n` (syntax check) accepts the result. This catches escape strategies
        // that look right per-character but break the surrounding zsh quoting. Skipped on
        // hosts without zsh.
        let inputs = [
            "plain text",
            "with ] bracket",
            "with : colon",
            "with \\ backslash",
            "with 'quote'",
            "with $variable",
            "all of \\]:'$ together",
            "embedded\nnewline\ttab",
        ];
        // Early probe: if zsh isn't installed, skip without running the loop.
        if zsh_syntax_check("true\n").is_none() {
            eprintln!("skipping: zsh not installed on this host");
            return;
        }
        for input in inputs {
            let escaped = escape_zsh_help(input);
            let spec = format!("_arguments '--foo[{escaped}]'\n");
            match zsh_syntax_check(&spec) {
                Some(Ok(())) => {}
                Some(Err(stderr)) => panic!(
                    "zsh -n rejected spec for input {input:?} (escaped: {escaped:?}):\nspec: {spec}stderr: {stderr}",
                ),
                None => panic!("zsh disappeared mid-test for input {input:?}"),
            }
        }
    }

    #[test]
    fn escape_zsh_help_collapses_newlines() {
        let escaped = escape_zsh_help("line1\nline2\ttabbed");
        assert!(!escaped.contains('\n'));
        assert!(!escaped.contains('\t'));
    }

    #[test]
    fn introspected_audit_flags_are_not_empty() {
        let flags = introspect_audit_flags();
        assert!(!flags.is_empty());
        assert!(flags.iter().any(|f| f.contains("--json")));
        assert!(flags.iter().any(|f| f.contains("--porcelain")));
        assert!(flags.iter().any(|f| f.contains("--verbose")));
        assert!(flags.iter().any(|f| f.contains("--tools")));
        assert!(flags.iter().any(|f| f.contains("--subprocess")));
    }
}
