//! Custom zsh completion generator for the git-tidy dispatcher.
//!
//! Generates a `_git-tidy` zsh completion function that:
//! - Completes dispatch aliases (from `TOOL_SPECS`) at position 1
//! - Delegates to per-tool completers (`_git-<tool>-tidy`) for deeper args
//! - Completes `audit` flags via clap introspection

use std::io::{self, Write};

use clap::CommandFactory;

use crate::cli;
use crate::types::TOOL_SPECS;

/// Generate a custom zsh completion script for `git-tidy`.
pub fn generate_zsh(out: &mut dyn Write) -> io::Result<()> {
    writeln!(out, "#compdef git-tidy")?;
    writeln!(out)?;
    writeln!(out, "# Auto-generated by git-tidy. Do not edit.")?;
    writeln!(out)?;

    // Collect all aliases for the compadd list
    let mut aliases: Vec<&str> = Vec::new();
    for spec in TOOL_SPECS {
        for alias in spec.aliases {
            aliases.push(alias);
        }
    }
    aliases.push("audit");

    // Introspect audit flags from clap
    let audit_flags = introspect_audit_flags();

    // Build the zsh function
    writeln!(out, "_git-tidy() {{")?;
    writeln!(out, "  local curcontext=\"$curcontext\" state line")?;
    writeln!(out, "  typeset -A opt_args")?;
    writeln!(out)?;
    writeln!(out, "  _arguments -C '1:command:->cmd' '*::arg:->args'")?;
    writeln!(out)?;
    writeln!(out, "  case $state in")?;

    // cmd state: complete aliases + audit
    writeln!(out, "    cmd)")?;
    write!(out, "      local -a commands=(")?;
    for alias in &aliases {
        write!(out, " '{alias}'")?;
    }
    writeln!(out, " )")?;
    writeln!(out, "      _describe 'command' commands")?;
    writeln!(out, "      ;;")?;

    // args state: delegate to sub-tool completers or complete audit flags
    writeln!(out, "    args)")?;
    writeln!(out, "      case ${{line[1]}} in")?;

    // For each tool spec, map all its aliases to the tool's completer
    for spec in TOOL_SPECS {
        let patterns: Vec<&str> = spec.aliases.to_vec();
        let pattern = patterns.join("|");
        writeln!(out, "        {pattern})")?;
        writeln!(
            out,
            "          _dispatch {} {} \"$@\"",
            spec.binary, spec.binary
        )?;
        writeln!(out, "          ;;")?;
    }

    // audit subcommand
    writeln!(out, "        audit)")?;
    write!(out, "          _arguments")?;
    for flag in &audit_flags {
        write!(out, " '{flag}'")?;
    }
    writeln!(out)?;
    writeln!(out, "          ;;")?;

    writeln!(out, "      esac")?;
    writeln!(out, "      ;;")?;
    writeln!(out, "  esac")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Conditional registration: only if _git-tidy isn't already defined
    writeln!(out, "(( $+functions[_git-tidy] )) || _git-tidy \"$@\"")?;

    Ok(())
}

/// Extract audit subcommand flags from the clap `Command` struct.
fn introspect_audit_flags() -> Vec<String> {
    let cmd = cli::Cli::command();
    let mut flags = Vec::new();

    for sub in cmd.get_subcommands() {
        if sub.get_name() == "audit" {
            for arg in sub.get_arguments() {
                if arg.get_id() == "help" {
                    continue;
                }
                let long = arg.get_long().unwrap_or_default();
                if !long.is_empty() {
                    let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
                    flags.push(format!("--{long}[{help}]"));
                }
            }
            break;
        }
    }

    flags
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated_output() -> String {
        let mut buf = Vec::new();
        generate_zsh(&mut buf).unwrap();
        String::from_utf8(buf).unwrap()
    }

    #[test]
    fn output_starts_with_compdef() {
        let output = generated_output();
        assert!(output.starts_with("#compdef git-tidy"));
    }

    #[test]
    fn output_contains_all_tool_aliases() {
        let output = generated_output();
        for spec in TOOL_SPECS {
            for alias in spec.aliases {
                assert!(
                    output.contains(&format!("'{alias}'")),
                    "missing alias {alias:?} in completions output"
                );
            }
        }
    }

    #[test]
    fn output_contains_audit() {
        let output = generated_output();
        assert!(output.contains("'audit'"));
    }

    #[test]
    fn output_contains_audit_flags() {
        let output = generated_output();
        assert!(output.contains("--json"), "missing --json audit flag");
        assert!(
            output.contains("--porcelain"),
            "missing --porcelain audit flag"
        );
        assert!(output.contains("--verbose"), "missing --verbose audit flag");
        assert!(output.contains("--tools"), "missing --tools audit flag");
        assert!(
            output.contains("--subprocess"),
            "missing --subprocess audit flag"
        );
    }

    #[test]
    fn output_contains_tool_delegation() {
        let output = generated_output();
        for spec in TOOL_SPECS {
            assert!(
                output.contains(spec.binary),
                "missing delegation for {}",
                spec.binary
            );
        }
    }

    #[test]
    fn output_contains_conditional_registration() {
        let output = generated_output();
        assert!(output.contains("$+functions[_git-tidy]"));
    }

    #[test]
    fn introspected_audit_flags_are_not_empty() {
        let flags = introspect_audit_flags();
        assert!(!flags.is_empty());
        assert!(flags.iter().any(|f| f.contains("--json")));
        assert!(flags.iter().any(|f| f.contains("--porcelain")));
        assert!(flags.iter().any(|f| f.contains("--verbose")));
        assert!(flags.iter().any(|f| f.contains("--tools")));
        assert!(flags.iter().any(|f| f.contains("--subprocess")));
    }
}
